layer1:
  P: 512
  Q: 1
  C: 768
  K: 2304
  R: 1
  S: 1
  stride: 1
  padding: 1
layer2:
  P: 512
  Q: 1
  C: 768
  K: 512
  R: 1
  S: 1
  stride: 1
  padding: 1
layer3:
  P: 512
  Q: 1
  C: 512
  K: 768
  R: 1
  S: 1
  stride: 1
  padding: 1
layer4:
  P: 512
  Q: 1
  C: 768
  K: 768
  R: 1
  S: 1
  stride: 1
  padding: 1
layer5:
  P: 512
  Q: 1
  C: 768
  K: 3072
  R: 1
  S: 1
  stride: 1
  padding: 1
layer6:
  P: 512
  Q: 1
  C: 3072
  K: 768
  R: 1
  S: 1
  stride: 1
  padding: 1
layer_name_dict:
  layer1: layer1
  layer2: layer2
  layer3: layer3
  layer4: layer4
  layer5: layer5
  layer6: layer6
  layer7: layer1
  layer8: layer2
  layer9: layer3
  layer10: layer4
  layer11: layer5
  layer12: layer6
  layer13: layer1
  layer14: layer2
  layer15: layer3
  layer16: layer4
  layer17: layer5
  layer18: layer6
  layer19: layer1
  layer20: layer2
  layer21: layer3
  layer22: layer4
  layer23: layer5
  layer24: layer6
  layer25: layer1
  layer26: layer2
  layer27: layer3
  layer28: layer4
  layer29: layer5
  layer30: layer6
  layer31: layer1
  layer32: layer2
  layer33: layer3
  layer34: layer4
  layer35: layer5
  layer36: layer6
  layer37: layer1
  layer38: layer2
  layer39: layer3
  layer40: layer4
  layer41: layer5
  layer42: layer6
  layer43: layer1
  layer44: layer2
  layer45: layer3
  layer46: layer4
  layer47: layer5
  layer48: layer6
  layer49: layer1
  layer50: layer2
  layer51: layer3
  layer52: layer4
  layer53: layer5
  layer54: layer6
  layer55: layer1
  layer56: layer2
  layer57: layer3
  layer58: layer4
  layer59: layer5
  layer60: layer6
  layer61: layer1
  layer62: layer2
  layer63: layer3
  layer64: layer4
  layer65: layer5
  layer66: layer6
  layer67: layer1
  layer68: layer2
  layer69: layer3
  layer70: layer4
  layer71: layer5
  layer72: layer6

