layer1:
  P: 112
  Q: 112
  C: 3
  K: 32
  R: 3
  S: 3
  stride: 2
  padding: 1
layer2:
  P: 56
  Q: 56
  C: 32
  K: 64
  R: 3
  S: 3
  stride: 2
  padding: 1
layer3:
  P: 56
  Q: 56
  C: 64
  K: 128
  R: 3
  S: 3
  stride: 1
  padding: 1
layer4:
  P: 56
  Q: 56
  C: 128
  K: 64
  R: 1
  S: 1
  stride: 1
  padding: 0
layer5:
  P: 28
  Q: 28
  C: 64
  K: 128
  R: 3
  S: 3
  stride: 2
  padding: 1
layer6:
  P: 28
  Q: 28
  C: 128
  K: 256
  R: 3
  S: 3
  stride: 1
  padding: 1
layer7:
  P: 28
  Q: 28
  C: 256
  K: 128
  R: 1
  S: 1
  stride: 1
  padding: 0
layer8:
  P: 14
  Q: 14
  C: 128
  K: 256
  R: 3
  S: 3
  stride: 2
  padding: 1
layer9:
  P: 14
  Q: 14
  C: 256
  K: 512
  R: 3
  S: 3
  stride: 1
  padding: 1
layer10:
  P: 14
  Q: 14
  C: 512
  K: 256
  R: 1
  S: 1
  stride: 1
  padding: 0
layer13:
  P: 7
  Q: 7
  C: 256
  K: 512
  R: 3
  S: 3
  stride: 2
  padding: 1
layer14:
  P: 7
  Q: 7
  C: 512
  K: 1024
  R: 3
  S: 3
  stride: 1
  padding: 1
layer15:
  P: 7
  Q: 7
  C: 1024
  K: 512
  R: 1
  S: 1
  stride: 1
  padding: 0
layer19:
  P: 7
  Q: 7
  C: 1024
  K: 1000
  R: 3
  S: 3
  stride: 1
  padding: 1
layer_name_dict:
  layer1: layer1
  layer2: layer2
  layer3: layer3
  layer4: layer4
  layer5: layer5
  layer6: layer6
  layer7: layer7
  layer8: layer8
  layer9: layer9
  layer10: layer10
  layer11: layer9
  layer12: layer10
  layer13: layer13
  layer14: layer14
  layer15: layer15
  layer16: layer14
  layer17: layer15
  layer18: layer14
  layer19: layer19

