layer1:
  P: 256
  Q: 1
  C: 2048
  K: 128
  R: 1
  S: 1
  stride: 1
  padding: 1
layer2:
  P: 128
  Q: 1
  C: 2048
  K: 64
  R: 1
  S: 1
  stride: 1
  padding: 1
layer3:
  P: 256
  Q: 1
  C: 2048
  K: 256
  R: 1
  S: 1
  stride: 1
  padding: 1
layer4:
  P: 2048
  Q: 1
  C: 256
  K: 256
  R: 1
  S: 1
  stride: 1
  padding: 1
layer6:
  P: 2048
  Q: 1
  C: 256
  K: 128
  R: 1
  S: 1
  stride: 1
  padding: 1
layer7:
  P: 2048
  Q: 1
  C: 128
  K: 256
  R: 1
  S: 1
  stride: 1
  padding: 1
layer8:
  P: 2048
  Q: 1
  C: 64
  K: 128
  R: 1
  S: 1
  stride: 1
  padding: 1
layer9:
  P: 2048
  Q: 1
  C: 128
  K: 64
  R: 1
  S: 1
  stride: 1
  padding: 1
layer10:
  P: 128
  Q: 1
  C: 2048
  K: 1
  R: 1
  S: 1
  stride: 1
  padding: 1
layer11:
  P: 2048
  Q: 1
  C: 128
  K: 1
  R: 1
  S: 1
  stride: 1
  padding: 1
layer12:
  P: 2048
  Q: 1
  C: 1
  K: 128
  R: 1
  S: 1
  stride: 1
  padding: 1
layer_name_dict:
  layer1: layer1
  layer2: layer2
  layer3: layer3
  layer4: layer4
  layer5: layer4
  layer6: layer6
  layer7: layer7
  layer8: layer8
  layer9: layer9
  layer10: layer10
  layer11: layer11
  layer12: layer12

