layer1:
  P: 112
  Q: 112
  C: 3
  K: 64
  R: 7
  S: 7
  stride: 2
  padding: 3
layer2:
  P: 56
  Q: 56
  C: 64
  K: 64
  R: 3
  S: 3
  stride: 1
  padding: 1
layer6:
  P: 28
  Q: 28
  C: 64
  K: 128
  R: 3
  S: 3
  stride: 2
  padding: 1
layer7:
  P: 28
  Q: 28
  C: 128
  K: 128
  R: 3
  S: 3
  stride: 1
  padding: 1
layer10:
  P: 14
  Q: 14
  C: 128
  K: 256
  R: 3
  S: 3
  stride: 2
  padding: 1
layer11:
  P: 14
  Q: 14
  C: 256
  K: 256
  R: 3
  S: 3
  stride: 1
  padding: 1
layer14:
  P: 7
  Q: 7
  C: 256
  K: 512
  R: 3
  S: 3
  stride: 2
  padding: 1
layer15:
  P: 7
  Q: 7
  C: 512
  K: 512
  R: 3
  S: 3
  stride: 1
  padding: 1
layer_name_dict:
  layer1: layer1
  layer2: layer2
  layer3: layer2
  layer4: layer2
  layer5: layer2
  layer6: layer6
  layer7: layer7
  layer8: layer7
  layer9: layer7
  layer10: layer10
  layer11: layer11
  layer12: layer11
  layer13: layer11
  layer14: layer14
  layer15: layer15
  layer16: layer15
  layer17: layer15

