layer1:
  P: 570
  Q: 570
  C: 1
  K: 64
  R: 3
  S: 3
  stride: 1
  padding: 1
layer2:
  P: 568
  Q: 568
  C: 64
  K: 64
  R: 3
  S: 3
  stride: 1
  padding: 1
layer3:
  P: 282
  Q: 282
  C: 64
  K: 128
  R: 3
  S: 3
  stride: 1
  padding: 1
layer4:
  P: 140
  Q: 140
  C: 128
  K: 128
  R: 3
  S: 3
  stride: 1
  padding: 1
layer5:
  P: 138
  Q: 138
  C: 128
  K: 256
  R: 3
  S: 3
  stride: 1
  padding: 1
layer6:
  P: 136
  Q: 136
  C: 256
  K: 256
  R: 3
  S: 3
  stride: 1
  padding: 1
layer7:
  P: 66
  Q: 66
  C: 256
  K: 512
  R: 3
  S: 3
  stride: 1
  padding: 1
layer8:
  P: 64
  Q: 64
  C: 512
  K: 512
  R: 3
  S: 3
  stride: 1
  padding: 1
layer9:
  P: 32
  Q: 32
  C: 512
  K: 1024
  R: 3
  S: 3
  stride: 1
  padding: 1
layer10:
  P: 28
  Q: 28
  C: 1024
  K: 1024
  R: 3
  S: 3
  stride: 1
  padding: 1
layer11:
  P: 56
  Q: 56
  C: 1024
  K: 512
  R: 2
  S: 2
  stride: 1
  padding: 1
layer12:
  P: 54
  Q: 54
  C: 1024
  K: 512
  R: 3
  S: 3
  stride: 1
  padding: 1
layer13:
  P: 52
  Q: 52
  C: 512
  K: 512
  R: 3
  S: 3
  stride: 1
  padding: 1
layer14:
  P: 104
  Q: 104
  C: 512
  K: 512
  R: 2
  S: 2
  stride: 1
  padding: 1
layer15:
  P: 102
  Q: 102
  C: 512
  K: 256
  R: 3
  S: 3
  stride: 1
  padding: 1
layer16:
  P: 100
  Q: 100
  C: 256
  K: 256
  R: 3
  S: 3
  stride: 1
  padding: 1
layer17:
  P: 200
  Q: 200
  C: 256
  K: 128
  R: 2
  S: 2
  stride: 1
  padding: 1
layer18:
  P: 198
  Q: 198
  C: 128
  K: 128
  R: 3
  S: 3
  stride: 1
  padding: 1
layer19:
  P: 196
  Q: 196
  C: 128
  K: 128
  R: 3
  S: 3
  stride: 1
  padding: 1
layer20:
  P: 392
  Q: 392
  C: 128
  K: 128
  R: 2
  S: 2
  stride: 1
  padding: 1
layer21:
  P: 390
  Q: 390
  C: 128
  K: 64
  R: 3
  S: 3
  stride: 1
  padding: 1
layer22:
  P: 388
  Q: 388
  C: 64
  K: 64
  R: 3
  S: 3
  stride: 1
  padding: 1
layer23:
  P: 388
  Q: 388
  C: 64
  K: 2
  R: 1
  S: 1
  stride: 1
  padding: 1
layer_name_dict:
  layer1: layer1
  layer2: layer2
  layer3: layer3
  layer4: layer4
  layer5: layer5
  layer6: layer6
  layer7: layer7
  layer8: layer8
  layer9: layer9
  layer10: layer10
  layer11: layer11
  layer12: layer12
  layer13: layer13
  layer14: layer14
  layer15: layer15
  layer16: layer16
  layer17: layer17
  layer18: layer18
  layer19: layer19
  layer20: layer20
  layer21: layer21
  layer22: layer22
  layer23: layer23

